### PR TITLE
Added the ability to zoom in and out using the mouse wheel. 

### PR DESCRIPTION
**Pull request by SeleDreams**
Zooms vertically with shortcut+wheel and horizontally with shortcut+alt+wheel.

### CODE REVIEW

**Comment by VocAddict** [comment]
I think it may be best to allow persons to choose what convention they would want for vertical and horizontal zooming seeing how some common music software would have horizontal zooming without the need of an extra key.

Personally, I prefer the way it is in this PR but it would be best to give person the choose to choose their way to zoom, especially when they're used to one thing and they have to do the exact opposite because of one software. It gets frustrating real quick.

**Comment by titinko** [comment]
One of the features that I haven't gotten around to coding is a hotkey customizer as part of User Preferences.

Will merge these changes now, although it's worth noting that zooming is extremely poorly optimized right now making smooth/fast zooming impossible.  I do plan on improving it by the 0.5 release.

**Comment by SeleDreams** [comment]
> I think it may be best to allow persons to choose what convention they would want for vertical and horizontal zooming seeing how some common music software would have horizontal zooming without the need of an extra key.
> 
> Personally, I prefer the way it is in this PR but it would be best to give person the choose to choose their way to zoom, especially when they're used to one thing and they have to do the exact opposite because of one software. It gets frustrating real quick.

originally i wanted to do it the vocaloid 5 way because vocaloid 5 is a reference, vocaloid 5 itself following the studio one way, but because the shift key wasn't recognized i ended up going with alt

but yes it would be nice for users to be able to modify it

**Comment by SeleDreams** [comment]
> One of the features that I haven't gotten around to coding is a hotkey customizer as part of User Preferences.
> 
> Will merge these changes now, although it's worth noting that zooming is extremely poorly optimized right now making smooth/fast zooming impossible. I do plan on improving it by the 0.5 release.

one suggestion would be for the zoom feature to take a float too to be able to zoom as quick as the scroll delta rather than always incrementing by 1 everytime

**Pull request merged**
